### PR TITLE
Update Sauce Connect download links/sha1.

### PR DESCRIPTION
**Pull request by ldx**

### CODE REVIEW

**Comment by siemiatj** [comment]
LGTM !

**Comment by colinsauce** [comment]
:shipit: :rocket:

**Comment by ldx** [comment]
@colinsauce I saw you also had a branch with the same changes, should that be merged instead?

**Comment by colinsauce** [comment]
@ldx I did then realized you made one. Let's use yours. I'll deploy this meow.

**Comment by colinsauce** [comment]
it's out

**Pull request merged**
