### PR TITLE
updated caps to have lower camel case

### PR DESCRIPTION
**Pull request by colinsauce**
**Ticket**: [SUP-44](https://saucedev.atlassian.net/browse/SUP-44)
@saucyallison please review

#### Problem

When looking at the test-config page the capabilities are shown with dashes. We'd like them to be lower camel cased.

#### Solution

Change them to match that case

#### Comments
Would love a second pair of eyes on this to make sure I didn't miss or or mess one up :)

#### Checklist

- [ ] Is there any cruft that should be removed along with this code change? [comment if yes]
- [ ] Is that code change resulting in any SQL query changes to the database? [comment if yes]
- [ ] Have you inspected queries that are run on the DB by the changed code? [comment if yes]
- [ ] Is that code change resulting in any performance changes to the application)? [comment if yes]

### CODE REVIEW

**Comment by saucyallison** [comment]
Cool! Think I found a few you missed, so let's see what you think:

## Selenium RC:
 '{"username": "your username here",
   "**access-key**": "your access key here",
   "os": "Windows 8",
   "browser": "firefox",
   "**browser-version**": "29"}'

## Accepted Keys:
**custom-data**: JSON object
      "**custom-data**": {

## Disabling Video Recording
As an alternative, the **video-upload-on-pass setting** will let you discard videos for passing tests identified using thepassed setting (*and fix link spacing :)*)

## Internet Explorer Driver Version
The specific version of the IE Driver executable can be customized using the **iedriver-version** key.

..wow we can embed test results? that's way rad!
anyway that's what I found, everything else looks great! thanks for doing this ^^

**Comment by colinsauce** [comment]
thanks @saucyallison for the input. I'm now going off the deep end and am searching all the docs

**Comment by colinsauce** [comment]
okay that's all the ones I found in the docs.

@saucyallison mind checking this again to make sure I didn't ruin everything?

**Comment by colinsauce** [comment]
okay that's all the ones I found in the docs.

@saucyallison mind checking this again to make sure I didn't ruin everything?

**Comment by saucyallison** [comment]
@colinsauce I'm happy to! My eagle eyes have only caught these:

### In common_errors.md:

## ERROR user closed connection while waiting for command to complete

Similar to our `command-timeout`, this means that Selenium took a long time to run the command -- usually the act of loading a page -- and your test runner shut down the test before it might have timed out on Sauce's end.

## Unsupported OS/browser/version combo

Check to make sure that the browser, `browser-version`, and platform settings you're using are in our supported list of platforms.
WHOA WHOA hold up! "browser-version" actually does nothing at the moment, we should change that to just `version`


### In rest_api.md:

## Update job
...
`custom-data`: [JSON] a set of key-value pairs with any extra info that a user would like to add to the job. Note that the max data allowed is 64KB

          "`custom-data`": {"source": "Testing REST API"}}'

That's everything, awesome job!!

**Comment by colinsauce** [comment]
Hey @saucyallison updated all but the rest api as those values need to stay. To change those it'll have to be in resto

**Comment by saucyallison** [comment]
Perfect @colinsauce ! LGTM, STS

**Pull request merged**
