### PR TITLE
Sauce Connect docs updates.

### PR DESCRIPTION
**Pull request by ldx**
Ping @theCampbell @saucyallison @colinsauce

### CODE REVIEW

**Comment by colinsauce** [comment]
LGTM @saucyallison @theCampbell do you object?

Nice to see we made making multiple tunnels easier \o/

**Comment by colinsauce** [comment]
ping @saucyallison @theCampbell

**Comment by saucyallison** [comment]
oh my bad, I'm sorry!

looks great to me, thanks for doing this @ldx!

**Comment by theCampbell** [comment]
LGTM as well (so for being late).

**Pull request merged**
