### PR TITLE
Update Jenkins tutorial to reference fields included in latest version of the Sauce Jenkins plugin

### PR DESCRIPTION
**Pull request by rossrowe**
This pull request includes some updates to the Jenkins tutorial (to reference the fields available in the latest version), as well as to the Java tutorial (to amend the Maven archetype command to remove references to the cloudbees repository)

### CODE REVIEW

**Comment by rossrowe** [comment]
@theCampbell @saucyallison @colinsauce, would you guys mind taking a look and let me know if the changes are okay?

**Comment by theCampbell** [comment]
looks good to me

**Comment by saucyallison** [comment]
Looks great - thank you @rossrowe !

**Comment by colinsauce** [comment]
Thanks @rossrowe !

**Pull request merged**
