### PR TITLE
Fix raw link for 'install_tutorial_ruby.sh'

### PR DESCRIPTION
**Pull request by DylanLacey**

### CODE REVIEW

**Comment by colinsauce** [comment]
LGTM @DylanLacey !

**Comment by DylanLacey** [comment]
A customer complained that this link wasn't working for her;  Hey @colinsauce Can you try cur'ing the new link and seeing if you have any issues?

**Comment by colinsauce** [comment]
Of coruse @DylanLacey. It works on my laptop on the remote wifi in LAX;
```
[14:29:22 colinpade@Colins-MacBook-Air 19476]$  curl https://raw.githubusercontent.com/saucelabs/appium-tutorial/master/bin/install_tutorial_ruby.sh
#!/usr/bin/env bash

# remote invocation:
# curl -L https://raw.github.com/saucelabs/appium-tutorial/master/bin/install_tutorial_ruby.sh | bash


# don't install all the documentation at the moment
GEM_INSTALL_OPTS="--no-ri --no-rdoc"
GEMFILE_URL=https://raw.githubusercontent.com/appium/sample-code/master/sample-code/examples/ruby/Gemfile
TEST_FILE_URL=https://raw.githubusercontent.com/appium/sample-code/master/sample-code/examples/ruby/sauce_example.rb

if ! which ruby > /dev/null; then
  echo "No Ruby installation found"
  exit
fi

if ! gem list bundler | grep '^bundler (' > /dev/null; then
  echo "Installing Bundler"
  gem install $GEM_INSTALL_OPTS bundler
fi

echo "Downloading Gemfile to the current directory"
curl -L $GEMFILE_URL > Gemfile

echo "Installing gems from Gemfile"
bundle install

echo "Downloading SauceTest.rb to the current directory"
curl -L $TEST_FILE_URL > SauceTest.rb
```

Here is the old link;
```
[08:40:28 colinpade@Colins-MacBook-Air 19476]$  curl https://raw.github.com/saucelabs/appium-tutorial/master/bin/install_tutorial_ruby.sh
[08:41:34 colinpade@Colins-MacBook-Air 19476]$ 
```

Is there something with their firewall or internet connectivity?

**Comment by DylanLacey** [comment]
I think it's their net.  Irrespectiveguardless, this PR got merged by another PR because I don't know how to Git.

**Pull request merged**
